backend:
  accessToken: ""
  enableWebdav: false
  enableFileDatabase: false
  performance:
    whiteboardInfoBroadcastFreq: 1

frontend:
  onWhiteboardLoad:
    setReadOnly: false
    displayInfo: false

  showSmallestScreenIndicator: true
  imageDownloadFormat: "png"
  imageURL: ""
  drawBackgroundGrid: false
  backgroundGridImage: "bg_grid.png"

  performance:
    refreshInfoFreq: 5

    pointerEventsThrottling:
      - fromUserCount: 0

        minDistDelta: 1

        maxFreq: 30
      - fromUserCount: 10
        minDistDelta: 5
        maxFreq: 10
